import type { Plant } from "./CartSlice"

export const plantsData: Plant[] = [
  // Plantas de Interior
  {
    id: 1,
    name: "Monstera Deliciosa",
    category: "Plantas de Interior",
    price: 45.99,
    image: "/monstera-deliciosa-tropical-houseplant.jpg",
    description: "Folhas grandes e exuberantes, perfeita para ambientes internos com luz indireta",
  },
  {
    id: 2,
    name: "Pothos Dourado",
    category: "Plantas de Interior",
    price: 24.99,
    image: "/golden-pothos-hanging-vine-plant.jpg",
    description: "Planta trepadeira de fácil cuidado, ideal para iniciantes",
  },
  {
    id: 3,
    name: "Espada-de-São-Jorge",
    category: "Plantas de Interior",
    price: 32.99,
    image: "/snake-plant-sansevieria-in-pot.jpg",
    description: "Extremamente resistente e purificadora de ar",
  },
  {
    id: 4,
    name: "Ficus Lyrata",
    category: "Plantas de Interior",
    price: 89.99,
    image: "/fiddle-leaf-fig-ficus-lyrata.jpg",
    description: "Árvore elegante com folhas em forma de violino",
  },
  {
    id: 5,
    name: "Zamioculca",
    category: "Plantas de Interior",
    price: 38.99,
    image: "/zz-plant-zamioculcas-zamiifolia.jpg",
    description: "Planta moderna e de baixa manutenção",
  },
  {
    id: 6,
    name: "Calathea Ornata",
    category: "Plantas de Interior",
    price: 42.99,
    image: "/calathea-ornata-pinstripe-plant.jpg",
    description: "Folhas listradas impressionantes e únicas",
  },

  // Suculentas
  {
    id: 7,
    name: "Echeveria Elegans",
    category: "Suculentas",
    price: 15.99,
    image: "/echeveria-elegans-succulent.jpg",
    description: "Roseta perfeita com tons azul-esverdeados",
  },
  {
    id: 8,
    name: "Aloe Vera",
    category: "Suculentas",
    price: 18.99,
    image: "/aloe-vera-medicinal-plant.jpg",
    description: "Propriedades medicinais e fácil cuidado",
  },
  {
    id: 9,
    name: "Crassula Ovata",
    category: "Suculentas",
    price: 22.99,
    image: "/jade-plant-crassula-ovata.jpg",
    description: "Planta da prosperidade, símbolo de boa sorte",
  },
  {
    id: 10,
    name: "Sedum Morganianum",
    category: "Suculentas",
    price: 28.99,
    image: "/burros-tail-sedum-morganianum.jpg",
    description: "Cascata de folhas suculentas em formato de lágrima",
  },
  {
    id: 11,
    name: "Haworthia Fasciata",
    category: "Suculentas",
    price: 16.99,
    image: "/zebra-haworthia-fasciata.jpg",
    description: "Listras brancas distintivas e compacta",
  },
  {
    id: 12,
    name: "Cactus Bola",
    category: "Suculentas",
    price: 19.99,
    image: "/golden-barrel-cactus.jpg",
    description: "Formato esférico perfeito com espinhos dourados",
  },

  // Plantas Aromáticas
  {
    id: 13,
    name: "Manjericão",
    category: "Plantas Aromáticas",
    price: 12.99,
    image: "/basil-herb-plant-pot.jpg",
    description: "Erva culinária fresca e aromática",
  },
  {
    id: 14,
    name: "Lavanda",
    category: "Plantas Aromáticas",
    price: 26.99,
    image: "/lavender-aromatic-herb.jpg",
    description: "Flores perfumadas e propriedades calmantes",
  },
  {
    id: 15,
    name: "Alecrim",
    category: "Plantas Aromáticas",
    price: 14.99,
    image: "/rosemary-herb-potted.jpg",
    description: "Sabor intenso para cozinha mediterrânea",
  },
  {
    id: 16,
    name: "Hortelã",
    category: "Plantas Aromáticas",
    price: 11.99,
    image: "/mint-herb-fresh.jpg",
    description: "Refrescante e versátil para chás e receitas",
  },
  {
    id: 17,
    name: "Tomilho",
    category: "Plantas Aromáticas",
    price: 13.99,
    image: "/thyme-herb-plant.jpg",
    description: "Erva delicada com aroma amadeirado",
  },
  {
    id: 18,
    name: "Sálvia",
    category: "Plantas Aromáticas",
    price: 15.99,
    image: "/sage-herb-plant.jpg",
    description: "Folhas aveludadas com propriedades medicinais",
  },
]
